(() => {
  'use strict';

  const e = (name, sound, rule, tags = ['any'], kind = 'word') => ({ name, sound, rule, tags, kind });

  const en = [
    e('Otto Mattic','Automatic','otto',['any'],'word'),
    e('Anna Sasin','An assassin','anna',['rogue'],'phrase'),
    e('Dee Zaster','Disaster','dee',['any'],'word'),
    e('Mona Lott','Moan a lot','mona',['any'],'phrase'),
    e('Ray Zinn','Raisin','ray',['casual'],'word'),
    e('Terry Fied','Terrified','terry',['any'],'word'),
    e('Joe King','Joking','joe',['any'],'word'),
    e('Paige Turner','Page turner','paige',['casual'],'phrase'),
    e('Carrie Oakey','Karaoke','carrie',['casual'],'word'),
    e('Mike Rafone','Microphone','mike',['casual'],'word'),
    e('Ella Vator','Elevator','ella',['scifi'],'word'),
    e('Manny Festo','Manifesto','manny',['any'],'word'),
    e('Terry Aki','Teriyaki','terry',['casual'],'word'),
    e('Barb Dwyer','Barbed wire','barb',['warrior'],'phrase'),
    e('Ray Darr','Radar','ray',['scifi'],'word'),
    e('Ali Gator','Alligator','ali',['casual'],'word'),
    e('Sue Flay','Soufflé','sue',['casual'],'word'),
    e('Tim Burr','Timber','tim',['warrior'],'word'),
    e('Gail Force','Gale force','gail',['mage'],'phrase'),
    e('Justin Time','Just in time','justin',['any'],'phrase'),
    e('Will Power','Willpower','will',['warrior'],'word'),
    e('Mo Mentum','Momentum','mo',['warrior'],'word'),
    e('Gene Rator','Generator','gene',['scifi'],'word'),
    e('Cy Clone','Cyclone','cy',['mage'],'word'),
    e('Ty Phoon','Typhoon','ty',['mage'],'word'),
    e('Stan Still','Stand still','stan',['warrior'],'phrase'),
    e('Rick O. Shay','Ricochet','rick',['rogue'],'word'),
    e('Cliff Hanger','Cliffhanger','cliff',['fantasy'],'word'),
    e('Noah Fence','No offense','noah',['any'],'phrase'),
    e('Barry Cade','Barricade','barry',['warrior'],'word'),
    e('Dee Cipher','Decipher','dee',['scifi'],'word'),
    e('Hugh Midity','Humidity','hugh',['any'],'word'),
    e('Phil A. Buster','Filibuster','phil',['any'],'word'),
    e('Al Gorithm','Algorithm','al',['scifi'],'word'),
    e('Ella Phant','Elephant','ella',['casual'],'word'),
    e('Phil Harmonic','Philharmonic','phil',['casual'],'word'),
    e('Barb Arian','Barbarian','barb',['warrior','fantasy'],'word'),
    e('Barry Tone','Baritone','barry',['casual'],'word'),
    e('Carrie B. Ann','Caribbean','carrie',['casual'],'word'),
    e('Gene Yus','Genius','gene',['any'],'word'),
    e('Penny Cillin','Penicillin','penny',['any'],'word'),
    e('Chris P. Bacon','Crispy bacon','chris',['casual'],'phrase'),
    e('Sal Ami','Salami','sal',['casual'],'word'),
    e('Mac Aroni','Macaroni','mac',['casual'],'word'),
    e('Cole Slaw','Coleslaw','cole',['casual'],'word'),
    e('Cole Down','Cooldown','cole',['any'],'game'),
    e('Mike Check','Mic check','mike',['any'],'phrase'),
    e('Mike Drop','Mic drop','mike',['any'],'phrase'),
    e('Paige Down','Page down','paige',['scifi'],'phrase'),
    e('Paige Number','Page number','paige',['casual'],'phrase'),
    e('Otto Save','Autosave','otto',['any'],'game'),
    e('Otto Attack','Auto attack','otto',['warrior'],'game'),
    e('Otto Loot','Auto-loot','otto',['any'],'game'),
    e('Otto Cast','Auto-cast','otto',['mage'],'game'),
    e('Otto Run','Autorun','otto',['any'],'game'),
    e('Anita Break','I need a break','anita',['any'],'phrase'),
    e('Anita Heal','I need a heal','anita',['mage'],'game'),
    e('Anita Potion','I need a potion','anita',['fantasy'],'game'),
    e('Anita Map','I need a map','anita',['any'],'game'),
    e('Anita Tank','I need a tank','anita',['warrior'],'game'),
    e('Anita Rez','I need a rez','anita',['fantasy'],'game'),
    e('Anita Buff','I need a buff','anita',['fantasy'],'game'),
    e('Anita Crit','I need a crit','anita',['any'],'game'),
    e('Ivana Win','I wanna win','ivana',['any'],'phrase'),
    e('Ivana Crit','I wanna crit','ivana',['any'],'game'),
    e('Ivana Loot','I wanna loot','ivana',['any'],'game'),
    e('Ivana Raid','I wanna raid','ivana',['fantasy'],'game'),
    e('Ivana Heal','I wanna heal','ivana',['mage'],'game'),
    e('Ivana Farm','I wanna farm','ivana',['casual'],'game'),
    e('Ivana Queue','I wanna queue','ivana',['any'],'game'),
    e('Ivana Craft','I wanna craft','ivana',['casual'],'game'),
    e('Ivana Respawn','I wanna respawn','ivana',['any'],'game'),
    e('Noah Mercy','No mercy','noah',['rogue','warrior'],'phrase'),
    e('Noah Chance','No chance','noah',['any'],'phrase'),
    e('Noah Clue','No clue','noah',['any'],'phrase'),
    e('Noah Mana','No mana','noah',['mage'],'game'),
    e('Noah Loot','No loot','noah',['any'],'game'),
    e('Noah Aim','No aim','noah',['scifi'],'game'),
    e('Noah Heals','No heals','noah',['fantasy'],'game'),
    e('Noah Way','No way','noah',['any'],'phrase'),
    e('Dewey Win','Do we win?','dewey',['any'],'phrase'),
    e('Dewey Loot','Do we loot?','dewey',['any'],'game'),
    e('Dewey Raid','Do we raid?','dewey',['fantasy'],'game'),
    e('Dewey Heal','Do we heal?','dewey',['mage'],'game'),
    e('Dewey Queue','Do we queue?','dewey',['any'],'game'),
    e('Ken I. Loot','Can I loot?','ken-i',['any'],'game'),
    e('Ken I. Roll','Can I roll?','ken-i',['any'],'game'),
    e('Ken I. Join','Can I join?','ken-i',['any'],'phrase'),
    e('Ken I. Heal','Can I heal?','ken-i',['mage'],'game'),
    e('Ken I. Tank','Can I tank?','ken-i',['warrior'],'game'),
    e('Ima Tank',"I'm a tank",'ima',['warrior'],'game'),
    e('Ima Rogue',"I'm a rogue",'ima',['rogue'],'game'),
    e('Ima Mage',"I'm a mage",'ima',['mage'],'game'),
    e('Ima Noob',"I'm a noob",'ima',['any'],'game'),
    e('Ima Healer',"I'm a healer",'ima',['fantasy'],'game'),
    e('Yuri Winner',"You're a winner",'yuri',['any'],'phrase'),
    e('Yuri Noob',"You're a noob",'yuri',['any'],'game'),
    e('Yuri Tank',"You're a tank",'yuri',['warrior'],'game'),
    e('Yuri Legend',"You're a legend",'yuri',['fantasy'],'phrase'),
    e('Will B. Back','Will be back','will-b',['any'],'phrase'),
    e('Will B. Fine','Will be fine','will-b',['any'],'phrase'),
    e('Will B. Ready','Will be ready','will-b',['any'],'phrase'),
    e('Al B. Back',"I'll be back",'al-b',['any'],'phrase'),
    e('Al B. Fine',"I'll be fine",'al-b',['any'],'phrase'),
    e('Al B. Ready',"I'll be ready",'al-b',['any'],'phrase'),
    e('Iona Sword','I own a sword','iona',['fantasy'],'game'),
    e('Iona Mount','I own a mount','iona',['fantasy'],'game'),
    e('Iona Guild','I own a guild','iona',['fantasy'],'game'),
    e('Iona Wand','I own a wand','iona',['mage'],'game'),
    e('May B. Lucky','Maybe lucky','may-b',['any'],'phrase'),
    e('May B. Next','Maybe next','may-b',['any'],'phrase'),
    e('Hugh Ready','You ready?','hugh-you',['any'],'phrase'),
    e('Hugh Mad','You mad?','hugh-you',['any'],'phrase')
  ];

  const mk = [
    e('Ana Liza','analiza','ana',['any'],'word'),
    e('Ana Log','analog','ana',['scifi'],'word'),
    e('Ana Nas','ananas','ana',['casual'],'word'),
    e('Ana Tomija','anatomija','ana',['any'],'word'),
    e('Kata Log','katalog','kata',['any'],'word'),
    e('Kata Pult','katapult','kata',['warrior'],'word'),
    e('Kata Strofa','katastrofa','kata',['any'],'word'),
    e('Kata Maran','katamaran','kata',['casual'],'word'),
    e('Kata Liza','kataliza','kata',['scifi'],'word'),
    e('Teo Rija','teorija','teo',['any'],'word'),
    e('Teo Rema','teorema','teo',['any'],'word'),
    e('Teo Log','teolog','teo',['fantasy'],'word'),
    e('Teo Logija','teologija','teo',['fantasy'],'word'),
    e('Mate Matika','matematika','mate',['any'],'word'),
    e('Mate Rija','materija','mate',['any'],'word'),
    e('Mate Rijal','materijal','mate',['any'],'word'),
    e('Gale Rija','galerija','gale',['casual'],'word'),
    e('Meta Fora','metafora','meta',['any'],'word'),
    e('Meta Data','metadata','meta',['scifi'],'word'),
    e('Para Doks','paradoks','para',['any'],'word'),
    e('Para Graf','paragraf','para',['any'],'word'),
    e('Para Metar','parametar','para',['scifi'],'word'),
    e('Para Normal','paranormal','para',['fantasy'],'word'),
    e('Poli Gon','poligon','poli',['any'],'word'),
    e('Poli Tika','politika','poli',['any'],'word'),
    e('Poli Cija','policija','poli',['any'],'word'),
    e('Poli Klinika','poliklinika','poli',['any'],'word'),
    e('Boro Vinka','borovinka','boro',['casual'],'word'),
    e('Manda Rina','mandarina','manda',['casual'],'word'),
    e('Kiki Riki','kikiriki','kiki',['casual'],'word'),
    e('Mari Nada','marinada','mari',['casual'],'word'),
    e('Mari Oneta','marioneta','mari',['casual'],'word'),
    e('Mili Gram','miligram','mili',['any'],'word'),
    e('Mili Metar','milimetar','mili',['any'],'word'),
    e('Mili Litar','mililitar','mili',['any'],'word'),
    e('Mile Nium','milenium','mile',['scifi'],'word'),
    e('Dino Saurus','dinosaurus','dino',['fantasy'],'word'),
    e('Kame Leon','kameleon','kame',['fantasy'],'word'),
    e('Kris Tal','kristal','kris',['fantasy'],'word'),
    e('Vera Nda','veranda','vera',['casual'],'word'),
    e('Kiro Praktik','kiropraktik','kiro',['any'],'word'),
    e('Viki Pedija','Vikipedija','viki',['scifi'],'word'),
    e('Rada R.','radar','rada',['scifi'],'word'),
    e('Laze R.','lazer','laze',['scifi'],'word'),
    e('Sava Na','savana','sava',['casual'],'word'),
    e('Toni K.','tonik','toni',['casual'],'word'),
    e('Domi No','domino','domi',['casual'],'word'),
    e('Domi Nant','dominant','domi',['warrior'],'word'),
    e('Domi Nanta','dominanta','domi',['warrior'],'word'),
    e('Mira Z.','miraz','mira',['any'],'word'),
    e('Kosta Nje','kostanje','kosta',['casual'],'word'),
    e('Pere Ca','pereca','pere',['casual'],'word'),
    e('Bobi Na','bobina','bobi',['scifi'],'word'),
    e('Bobi Ca','bobica','bobi',['casual'],'word'),
    e('Bate Rija','baterija','bate',['scifi'],'word'),
    e('Blago Dara M.','blagodaram','blago',['any'],'phrase'),
    e('Limo Nada','limonada','limo',['casual'],'word'),
    e('Maka Roni','makaroni','maka',['casual'],'word'),
    e('Pala Chinka','palachinka','pala',['casual'],'word'),
    e('Aero Drom','aerodrom','aero',['scifi'],'word'),
    e('Inter Net','internet','inter',['scifi'],'word'),
    e('Foto Graf','fotograf','foto',['casual'],'word'),
    e('Tele Fon','telefon','tele',['scifi'],'word'),
    e('Mega Fon','megafon','mega',['casual'],'word'),
    e('Mikro Fon','mikrofon','mikro',['casual'],'word'),
    e('Geo Graf','geograf','geo',['any'],'word'),
    e('Geo Metar','geometar','geo',['any'],'word'),
    e('Kilo Metar','kilometar','kilo',['any'],'word'),
    e('Kilo Gram','kilogram','kilo',['any'],'word'),
    e('Termo Metar','termometar','termo',['any'],'word'),
    e('Kale Ndar','kalendar','kale',['any'],'word'),
    e('Kame Ra','kamera','kame',['scifi'],'word'),
    e('Gaze La','gazela','gaze',['casual'],'word'),
    e('Dare Zliv','darezliv','dare',['any'],'word'),
    e('Pere Nje','perenje','pere',['casual'],'word'),
    e('Bore Nje','borenje','bore',['warrior'],'word'),
    e('Bori Se','bori se','bori',['warrior'],'phrase'),
    e('Miri Se','miri se','miri',['any'],'phrase'),
    e('Pero N.','peron','pero',['any'],'word'),
    e('Kole Ga','kolega','kole',['any'],'word'),
    e('Kole Kcija','kolekcija','kole',['casual'],'word'),
    e('Simo N.','Simon','simo',['any'],'word'),
    e('Vito Min','vitamin','vito',['casual'],'word'),
    e('Karo Tin','karotin','karo',['casual'],'word'),
    e('Meri Dijan','meridijan','meri',['any'],'word'),
    e('Meri Lo','merilo','meri',['any'],'word'),
    e('Avi On','avion','avi',['scifi'],'word'),
    e('Heli Kopter','helikopter','heli',['scifi'],'word'),
    e('Moto Cikl','motocikl','moto',['casual'],'word'),
    e('Tele Vizor','televizor','tele',['scifi'],'word'),
    e('Pro Gram','program','pro',['scifi'],'word'),
    e('Pro Cesor','procesor','pro',['scifi'],'word'),
    e('Moni Tor','monitor','moni',['scifi'],'word'),
    e('Digi Tal','digital','digi',['scifi'],'word'),
    e('Kri Tik','kritik','kri',['any'],'word'),
    e('Kri Tika','kritika','kri',['any'],'word')
  ];

  // Strength is a quality signal, not randomness. Strong entries are the ones that
  // read most naturally as person-like names while still sounding like the target.
  const enStrongRules = new Set(['otto','anna','dee','mona','ray','terry','joe','paige','carrie','mike','ella','manny','barb','ali','sue','tim','gail','justin','will','mo','gene','cy','ty','stan','rick','cliff','noah','barry','hugh','phil','al','penny','chris','sal','mac','cole']);
  const mkStrongRules = new Set(['ana','kata','teo','mate','gale','meta','boro','manda','kiki','mari','mile','dino','kame','kris','vera','kiro','viki','rada','laze','sava','toni','domi','mira','kosta','pere','bobi','bate','blago','limo','maka','meri']);
  const mkMediumRules = new Set(['mili','para','poli','gaze','dare','bore','bori','miri','pero','kole','vito','karo','kale','avi','moni']);
  en.forEach(x => { x.strength = enStrongRules.has(x.rule) ? 3 : 2; });
  mk.forEach(x => { x.strength = mkStrongRules.has(x.rule) ? 3 : (mkMediumRules.has(x.rule) ? 2 : 1); });

  window.PUNNY_PHONETIC_DATA = {
    en,
    mk,
    labels: {
      en: { pun:'phonetic pun', word:'sounds like a word', phrase:'sounds like a phrase', game:'game sound-alike' },
      mk: { pun:'fonetska igra', word:'zvuchi kako zbor', phrase:'zvuchi kako fraza', game:'gejmerska igra na zborovi' }
    }
  };
})();
